### ISSUE TITLE
Windows binary crash on startup

### ISSUE THREAD

**Issue by kotobdev** [Elpersonn/Retrocord-client#1]
![image](https://user-images.githubusercontent.com/59124164/126876933-c37fa2f1-ac19-45ec-8160-80b4f7a62151.png)

Steps to reproduce:
1: Launch program

:trollface:

**Comment by kotobdev** [comment]
Fixed in build currently outside GitHub- close error when uploaded

**Comment by Elpersonn** [comment]
Fixed build has been uploaded
